language: scala
dist: xenial
install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

scala:
   - 2.13.4

stages:
  - name: docs
  - name: release
    if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"

jobs:
  include:
    - stage: docs
    - env: TEST="docs"
      script:
        - sbt ++$TRAVIS_SCALA_VERSION router/fullOptJS::webpack
        - sbt docs/mdoc
        - sbt docs/makeMicrosite
        - mkdir -p router-docs/site
        - cp -R router-docs/target/site/* ./router-docs/site/
      deploy:
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: router-docs/site
        provider: pages
        skip_cleanup: true
        target-branch: gh-pages
        on:
          branch: master
    - stage: release
      script: sbt ci-release
