language: scala

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

scala:
   - 2.12.8
   
jobs:
  include:
    - stage: verify

      script:
        - sbt ++$TRAVIS_SCALA_VERSION router/fullOptJS::webpack
        - sbt docs/mdoc
        - sbt docs/makeMicrosite
        - mkdir -p router-docs/site
        - cp -R router-docs/target/site/* ./router-docs/site/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: router-docs/site
  target-branch: gh-pages
  on:
    branch: master  
