language: scala
dist: xenial
install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

scala_212: &scala_212 2.12.12
scala_213: &scala_213 2.13.4

stages:
  - name: docs
  - name: release
    if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"

jobs:
  include:
    - &all_tests
      stage: test
      env: TEST="all_tests"
      scala: *scala_212
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - <<: *all_tests
      env: TEST="all_tests"
      scala: *scala_213
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - env: TEST="styling"
      scala: *scala_213
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
    - stage: docs
    - env: TEST="docs"
      scala: *scala_213
      script:
        - sbt ++$TRAVIS_SCALA_VERSION router/fullOptJS::webpack
        - sbt ++$TRAVIS_SCALA_VERSION docs/mdoc
        - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite
        - mkdir -p router-docs/site
        - cp -R router-docs/target/site/* ./router-docs/site/
      deploy:
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: router-docs/site
        provider: pages
        skip_cleanup: true
        target-branch: gh-pages
        on:
          branch: master
    - stage: release
      script: sbt ++$TRAVIS_SCALA_VERSION ci-release
