name: Outwatch Router
baseurl: /outwatch-router
description: A router for outwatch
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.7
org: com.clovellytech
markdown: kramdown
